# Generated by Django 2.2.14 on 2020-07-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('logo_url', models.ImageField(upload_to='images/teams/')),
                ('club_state', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('image_url', models.ImageField(upload_to='images/players/')),
                ('player_jersey_no', models.SmallIntegerField()),
                ('Country', models.CharField(max_length=32)),
                ('matches', models.IntegerField(default=0)),
                ('run', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('fifties', models.SmallIntegerField(default=0)),
                ('hundreds', models.SmallIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Team')),
            ],
        ),
    ]
