# Generated by Django 2.2.14 on 2020-07-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.ImageField(default='images/players/default_image.png', upload_to='images/players/'),
        ),
    ]
