# Generated by Django 2.2.14 on 2020-07-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200730_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='main.Team')),
                ('right_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oppsite_team', to='main.Team')),
                ('winner_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='main.Team')),
            ],
        ),
    ]
