# Generated by Django 2.2.14 on 2020-07-31 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200731_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchyear',
            name='year',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2019)]),
        ),
    ]
