# Generated by Django 2.2.14 on 2020-08-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200731_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='year',
        ),
        migrations.DeleteModel(
            name='MatchYear',
        ),
    ]
