# Generated by Django 2.2.14 on 2020-08-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200802_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='winner_team',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
