# Generated by Django 2.2.14 on 2020-08-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200803_0400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
