# Generated by Django 2.2.14 on 2020-08-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200830_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.ImageField(default='media/images/players/default_image.png', upload_to='media/images/players/'),
        ),
    ]
