# Generated by Django 2.2.14 on 2020-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200830_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.ImageField(default='images/players/default_image.png', upload_to='images/players/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.ImageField(upload_to='images/teams/'),
        ),
    ]
